#!/usr/bin/env ruby

t=->(s){i=3;s.split(':').inject(0){|r,v| i=i-1;r+(60**i)*v.to_i}}
puts "输入开始时间：";b=t.call(gets)
puts "输入结束时间：";e=t.call(gets)

r=->(s){11.times.map{|i| s+3600*i+ 3600*i/11.0}}
puts "时针与分针重复：%s次" % [(r.call(0)+r.call(43200)).select {|v|v>=b && v<=e}.count]
